# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven Build Test

on:
  push:
    branches: [development]
  pull_request:
    branches: [main, development]

jobs:
  build-test:
    runs-on: ubuntu-latest
    # Check and executes only for development branch
    # if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Checkstyle check
        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn -B package --file pom.xml

