# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Commented for fast debugging
    # - name: Checkstyle check
    #   run: mvn checkstyle:check
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    # For testing making to deploy from development
    # Use main in production
    if: github.ref == 'refs/heads/development'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Commented for fast debugging
    # - name: Checkstyle check
    #   run: mvn checkstyle:check
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      # - name: Deploy app
      #   run: exit 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: REVISION=0.0.1
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/springstarter:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

